### ISSUE TITLE
Color Coding

### ISSUE THREAD

**Issue by mihelics** [BlueBrain/VessMorphoVis#14]
Thank you for considering my feature request for the VessMorphoVis plugin: I would like to encode the directions of the vessels as a color (x-alignment->R,y->G,z->B). I may want to encode other attributes in color, so I would love more control over the coloring of the vessel objects. Ideally, I would love it if the last three fields of the point coordinates comprising the vessel centerline locations in the .vmv file could be interpreted as RGB values for that specific location along the vessel.

Thank you,
Pleased user of VessMorphoVis

**Comment by marwan-abdellah** [comment]
@mihelics: can we have a quick call to discuss something for this feature?

**Comment by mihelics** [comment]
@marwan-abdellah Yes please. How do you want to do the call?

**Comment by marwan-abdellah** [comment]
@mihelics We can have a Skype or Zoom call next Monday at any time. Please email me for details. Thanks, 
P.S.  Have a look on the documentation of the current coloring schemes (https://github.com/BlueBrain/VessMorphoVis/wiki/Morphology-Reconstruction).

**Comment by marwan-abdellah** [comment]
Implemented.
