### ISSUE TITLE
Feature Request: directional color coding

### ISSUE THREAD

**Issue by mihelics** [BlueBrain/VessMorphoVis#23]
Please add a color map option that maps vessel direction at each point (by comparing change in position between each point and one or both neighbors) to colors: [ |dx|, |dy|, |dz| ] -> [ R, G, B ] where |dx|, |dy|, |dz| are the absolute-valued difference in position with respect to trace-location along vessel section.

**Comment by marwan-abdellah** [comment]
The feature has been implemented. You can visualize the morphology as a list of segments color coded based on the XYZ alignment of each segment. See the following examples:

![MORPHOLOGY_sample-1_FRONT](https://user-images.githubusercontent.com/1279443/136081197-611d1aa2-d999-4efb-b003-e65b1cf0afb6.png)

![MORPHOLOGY_sample-1_FRONT (1)](https://user-images.githubusercontent.com/1279443/136081220-f51d9ff6-95eb-46a3-a902-edec46c0ba12.png)

![MORPHOLOGY_sample-1_FRONT (3)](https://user-images.githubusercontent.com/1279443/136081247-b68bbe1f-ea8a-4cb8-bb0a-045a47de236d.png)

**Comment by mihelics** [comment]
Does X correspond to Red, Y to Green, and Z to Blue? I can't tell if it is working.

**Comment by marwan-abdellah** [comment]
Yes XYZ corresponds to RGB

**Comment by mihelics** [comment]
Hard to tell from the single perspective image.

![image](https://user-images.githubusercontent.com/45496077/136087057-6e661977-bfcd-4588-956a-c8ca008adee8.png)

**Comment by marwan-abdellah** [comment]
What the attachment is about?

**Comment by SamuelMihelic** [comment]
That is an MC Escher work that illustrates how a single perspective of a three-dimensional object can be misleading
