### ISSUE TITLE
Request of Access to Supplementary material

### ISSUE THREAD

**Issue by Paddy-Xu** [BlueBrain/VessMorphoVis#54]
Hi, 

Thanks for the great work and public-available software. I am particularly interested in the mesh generation. I can see most of the method details are in supplementary materials. However, it seems not able to retrieve the supplementary from the bioinformatics website. https://academic.oup.com/bioinformatics/article/36/Supplement_1/i534/5870503?login=false. 

May I ask if there is anywhere else I can find the supplementary materials? Otherwise, would you mind providing a pdf file?

Thanks a lot in advance!

**Comment by marwan-abdellah** [comment]
@Paddy-Xu Thanks for your interest. I hereby attach the supplementary document. Nonetheless, note that if you are mainly interested in **Meshing**, we would recommend you to use [Ultraliser](https://github.com/BlueBrain/Ultraliser), it is much more accurate and efficient at the same time. The paper can be found [here](https://academic.oup.com/bib/article/24/1/bbac491/6847753?login=false) with several use cases including large scale vascular meshing.  

HTH 

- Marwan 

[VessMorphoVis Supplement.pdf](https://github.com/BlueBrain/VessMorphoVis/files/11980874/VessMorphoVis.Supplement.pdf)

CC: @jplanasc

**Comment by Paddy-Xu** [comment]
@marwan-abdellah 
@jplanasc 
Thanks a lot! I looked through the other work you mentioned but indeed have some doubts. 

I have a vascular skeleton model with around 55K nodes, but it spans a dimension of around (21K * 11K * 14K) micro-meters with the smallest vessel with a radius around 10 micro-meters.

If I understand correctly, The method in Ultraliser requires an intermediate volume to rasterize the input morphology. Then in my case, I think it would require at least (probably even smaller) voxel size of at most 5 micro-meters to capture the 10 micro-meter vessels. This would end up with around (4K * 2K * 3K). It seems too heavy to be even loaded to memory. 

Therefore, I feel that Meta balls meshing based method makes more sense in my case, as the number of nodes in my case is not that large compared to the example used in the paper, but it seems to span a larger space.

Please correct me if I am wrong! Thanks again!

**Comment by marwan-abdellah** [comment]
@Paddy-Xu 

Ultraliser uses binary voxelization to reconstruct the intermediate volume. The volume you indicated (4k x 2k x 3k) is still relatively small for what Ultraliser can do. A 4k x 4k x 4k volume requires the following memory: Given that a single voxel is 1 single bit, the volume requires 4k x 4k x 4k memory = 64 Gbit memory = 8 Gbytes memory, which, I assume, is affordable on a machine with 16 Gbytes. Note that the meshing will requires a bit more memory, so in total you will need a machine with 32 Gbytes to construct an optimized mesh. If you wish, I can help you to create this mesh, I have a machine with 256 Gbytes of memory. 

Thanks,

**Comment by Paddy-Xu** [comment]
Thanks! I will prepare the format and send it to you.
